// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package frog_blossom_db

import (
	"database/sql"
	"time"
)

type Meta struct {
	ID              int64          `json:"id"`
	PageID          sql.NullInt64  `json:"page_id"`
	PostsID         sql.NullInt64  `json:"posts_id"`
	MetaTitle       sql.NullString `json:"meta_title"`
	MetaDescription sql.NullString `json:"meta_description"`
	MetaRobots      sql.NullString `json:"meta_robots"`
	MetaViewport    sql.NullString `json:"meta_viewport"`
	MetaCharset     sql.NullString `json:"meta_charset"`
	PageAmount      int64          `json:"page_amount"`
	SiteLanguage    sql.NullString `json:"site_language"`
	MetaKey         string         `json:"meta_key"`
	MetaValue       string         `json:"meta_value"`
}

type Page struct {
	ID             int64  `json:"id"`
	Domain         string `json:"domain"`
	PageAuthor     int64  `json:"page_author"`
	Title          string `json:"title"`
	Url            string `json:"url"`
	MenuOrder      int64  `json:"menu_order"`
	ComponentType  string `json:"component_type"`
	ComponentValue string `json:"component_value"`
	PageIdentifier string `json:"page_identifier"`
	OptionID       int64  `json:"option_id"`
	OptionName     string `json:"option_name"`
	OptionValue    string `json:"option_value"`
	OptionRequired bool   `json:"option_required"`
}

type Post struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	Author       string    `json:"author"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Status       string    `json:"status"`
	PublishedAt  time.Time `json:"published_at"`
	EditedAt     time.Time `json:"edited_at"`
	PostAuthor   int64     `json:"post_author"`
	PostMimeType string    `json:"post_mime_type"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Role      sql.NullString `json:"role"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	UserUrl   sql.NullString `json:"user_url"`
	Bio       sql.NullString `json:"bio"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
