// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package frog_blossom_db

import (
	"database/sql"
	"time"
)

type Meta struct {
	ID              int64          `json:"id"`
	PageID          sql.NullInt64  `json:"page_id"`
	PostsID         sql.NullInt64  `json:"posts_id"`
	MetaTitle       sql.NullString `json:"meta_title"`
	MetaDescription sql.NullString `json:"meta_description"`
	MetaRobots      sql.NullString `json:"meta_robots"`
	MetaOgImage     sql.NullString `json:"meta_og_image"`
	Locale          sql.NullString `json:"locale"`
	PageAmount      int64          `json:"page_amount"`
	SiteLanguage    sql.NullString `json:"site_language"`
	MetaKey         string         `json:"meta_key"`
	MetaValue       string         `json:"meta_value"`
}

type Page struct {
	ID             int64  `json:"id"`
	Domain         string `json:"domain"`
	AuthorID       int64  `json:"author_id"`
	PageAuthor     string `json:"page_author"`
	Title          string `json:"title"`
	Url            string `json:"url"`
	MenuOrder      int64  `json:"menu_order"`
	ComponentType  string `json:"component_type"`
	ComponentValue string `json:"component_value"`
	PageIdentifier string `json:"page_identifier"`
	OptionID       int64  `json:"option_id"`
	OptionName     string `json:"option_name"`
	OptionValue    string `json:"option_value"`
	OptionRequired bool   `json:"option_required"`
}

type Post struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	AuthorID     int64     `json:"author_id"`
	Url          string    `json:"url"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Status       string    `json:"status"`
	PublishedAt  time.Time `json:"published_at"`
	EditedAt     time.Time `json:"edited_at"`
	PostAuthor   string    `json:"post_author"`
	PostMimeType string    `json:"post_mime_type"`
	PublishedBy  string    `json:"published_by"`
	UpdatedBy    string    `json:"updated_by"`
}

type User struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	Email       string         `json:"email"`
	Password    string         `json:"password"`
	Role        string         `json:"role"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	UserUrl     sql.NullString `json:"user_url"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	IsDeleted   sql.NullBool   `json:"is_deleted"`
}
