// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package frog_blossom_db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Content struct {
	ID            int64         `json:"id"`
	Title         string        `json:"title"`
	Body          string        `json:"body"`
	AuthorID      int64         `json:"author_id"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
	Status        string        `json:"status"`
	PublishedAt   sql.NullTime  `json:"published_at"`
	EditedAt      sql.NullTime  `json:"edited_at"`
	PublishedByID sql.NullInt64 `json:"published_by_id"`
	ComponentID   int64         `json:"component_id"`
}

type ContentImage struct {
	ID          int64          `json:"id"`
	ContentID   sql.NullInt64  `json:"content_id"`
	FilePath    string         `json:"file_path"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	AltText     sql.NullString `json:"alt_text"`
}

type FormField struct {
	ID          int64  `json:"id"`
	ComponentID int64  `json:"component_id"`
	Label       string `json:"label"`
	Type        string `json:"type"`
	Required    bool   `json:"required"`
}

type Page struct {
	ID        int64  `json:"id"`
	WebsiteID int64  `json:"website_id"`
	Title     string `json:"title"`
	Url       string `json:"url"`
}

type PageComponent struct {
	ID            int64           `json:"id"`
	PageID        int64           `json:"page_id"`
	ComponentType string          `json:"component_type"`
	ComponentData json.RawMessage `json:"component_data"`
}

type Template struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Role      sql.NullString `json:"role"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	Bio       sql.NullString `json:"bio"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Website struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	Domain           string `json:"domain"`
	OwnerID          int64  `json:"owner_id"`
	SelectedTemplate int64  `json:"selected_template"`
}

type WebsiteTemplate struct {
	WebsiteID  sql.NullInt64 `json:"website_id"`
	TemplateID sql.NullInt64 `json:"template_id"`
}
