// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pages.sql

package frog_blossom_db

import (
	"context"
)

const createPages = `-- name: CreatePages :one
INSERT INTO pages (
  domain,
  author_id,
  page_author,
  title,
  url,
  menu_order,
  component_type,
  component_value,
  page_identifier,
  option_id,
  option_name,
  option_value,
  option_required
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, domain, author_id, page_author, title, url, menu_order, component_type, component_value, page_identifier, option_id, option_name, option_value, option_required
`

type CreatePagesParams struct {
	Domain         string `json:"domain"`
	AuthorID       int64  `json:"author_id"`
	PageAuthor     string `json:"page_author"`
	Title          string `json:"title"`
	Url            string `json:"url"`
	MenuOrder      int64  `json:"menu_order"`
	ComponentType  string `json:"component_type"`
	ComponentValue string `json:"component_value"`
	PageIdentifier string `json:"page_identifier"`
	OptionID       int64  `json:"option_id"`
	OptionName     string `json:"option_name"`
	OptionValue    string `json:"option_value"`
	OptionRequired bool   `json:"option_required"`
}

func (q *Queries) CreatePages(ctx context.Context, arg CreatePagesParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, createPages,
		arg.Domain,
		arg.AuthorID,
		arg.PageAuthor,
		arg.Title,
		arg.Url,
		arg.MenuOrder,
		arg.ComponentType,
		arg.ComponentValue,
		arg.PageIdentifier,
		arg.OptionID,
		arg.OptionName,
		arg.OptionValue,
		arg.OptionRequired,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AuthorID,
		&i.PageAuthor,
		&i.Title,
		&i.Url,
		&i.MenuOrder,
		&i.ComponentType,
		&i.ComponentValue,
		&i.PageIdentifier,
		&i.OptionID,
		&i.OptionName,
		&i.OptionValue,
		&i.OptionRequired,
	)
	return i, err
}

const deletePages = `-- name: DeletePages :exec
DELETE FROM pages
WHERE id = $1
`

func (q *Queries) DeletePages(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePages, id)
	return err
}

const getPages = `-- name: GetPages :one
SELECT id, domain, author_id, page_author, title, url, menu_order, component_type, component_value, page_identifier, option_id, option_name, option_value, option_required FROM pages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPages(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPages, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AuthorID,
		&i.PageAuthor,
		&i.Title,
		&i.Url,
		&i.MenuOrder,
		&i.ComponentType,
		&i.ComponentValue,
		&i.PageIdentifier,
		&i.OptionID,
		&i.OptionName,
		&i.OptionValue,
		&i.OptionRequired,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, domain, author_id, page_author, title, url, menu_order, component_type, component_value, page_identifier, option_id, option_name, option_value, option_required FROM pages
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.AuthorID,
			&i.PageAuthor,
			&i.Title,
			&i.Url,
			&i.MenuOrder,
			&i.ComponentType,
			&i.ComponentValue,
			&i.PageIdentifier,
			&i.OptionID,
			&i.OptionName,
			&i.OptionValue,
			&i.OptionRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePages = `-- name: UpdatePages :one
UPDATE pages
  SET domain = $2,
  author_id = $3,
  page_author = $4,
  title = $5,
  url = $6,
  menu_order = $7,
  component_type = $8,
  component_value = $9,
  page_identifier = $10,
  option_id = $11,
  option_name = $12,
  option_value = $13,
  option_required = $14
WHERE id = $1
RETURNING id, domain, author_id, page_author, title, url, menu_order, component_type, component_value, page_identifier, option_id, option_name, option_value, option_required
`

type UpdatePagesParams struct {
	ID             int64  `json:"id"`
	Domain         string `json:"domain"`
	AuthorID       int64  `json:"author_id"`
	PageAuthor     string `json:"page_author"`
	Title          string `json:"title"`
	Url            string `json:"url"`
	MenuOrder      int64  `json:"menu_order"`
	ComponentType  string `json:"component_type"`
	ComponentValue string `json:"component_value"`
	PageIdentifier string `json:"page_identifier"`
	OptionID       int64  `json:"option_id"`
	OptionName     string `json:"option_name"`
	OptionValue    string `json:"option_value"`
	OptionRequired bool   `json:"option_required"`
}

func (q *Queries) UpdatePages(ctx context.Context, arg UpdatePagesParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, updatePages,
		arg.ID,
		arg.Domain,
		arg.AuthorID,
		arg.PageAuthor,
		arg.Title,
		arg.Url,
		arg.MenuOrder,
		arg.ComponentType,
		arg.ComponentValue,
		arg.PageIdentifier,
		arg.OptionID,
		arg.OptionName,
		arg.OptionValue,
		arg.OptionRequired,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.AuthorID,
		&i.PageAuthor,
		&i.Title,
		&i.Url,
		&i.MenuOrder,
		&i.ComponentType,
		&i.ComponentValue,
		&i.PageIdentifier,
		&i.OptionID,
		&i.OptionName,
		&i.OptionValue,
		&i.OptionRequired,
	)
	return i, err
}
