// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: posts.sql

package db

import (
	"context"
	"time"
)

const createPosts = `-- name: CreatePosts :one
INSERT INTO posts (
  title,
  content,
  author_id,
  url,
  created_at,
  updated_at,
  status,
  published_at,
  edited_at,
  post_author,
  post_mime_type,
  published_by,
  updated_by
) VALUES (
  $1, $2, $3, $4, DEFAULT, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, title, content, author_id, url, created_at, updated_at, status, published_at, edited_at, post_author, post_mime_type, published_by, updated_by
`

type CreatePostsParams struct {
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	AuthorID     int64     `json:"author_id"`
	Url          string    `json:"url"`
	UpdatedAt    time.Time `json:"updated_at"`
	Status       string    `json:"status"`
	PublishedAt  time.Time `json:"published_at"`
	EditedAt     time.Time `json:"edited_at"`
	PostAuthor   string    `json:"post_author"`
	PostMimeType string    `json:"post_mime_type"`
	PublishedBy  string    `json:"published_by"`
	UpdatedBy    string    `json:"updated_by"`
}

func (q *Queries) CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPosts,
		arg.Title,
		arg.Content,
		arg.AuthorID,
		arg.Url,
		arg.UpdatedAt,
		arg.Status,
		arg.PublishedAt,
		arg.EditedAt,
		arg.PostAuthor,
		arg.PostMimeType,
		arg.PublishedBy,
		arg.UpdatedBy,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostAuthor,
		&i.PostMimeType,
		&i.PublishedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deletePosts = `-- name: DeletePosts :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePosts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePosts, id)
	return err
}

const getPosts = `-- name: GetPosts :one
SELECT id, title, content, author_id, url, created_at, updated_at, status, published_at, edited_at, post_author, post_mime_type, published_by, updated_by FROM posts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPosts(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPosts, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostAuthor,
		&i.PostMimeType,
		&i.PublishedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, content, author_id, url, created_at, updated_at, status, published_at, edited_at, post_author, post_mime_type, published_by, updated_by FROM posts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.PublishedAt,
			&i.EditedAt,
			&i.PostAuthor,
			&i.PostMimeType,
			&i.PublishedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosts = `-- name: UpdatePosts :one
UPDATE posts
  SET title = $2,
  content = $3,
  author_id = $4,
  url = $5,
  updated_at = $6,
  status = $7,
  published_at = $8,
  edited_at = $9,
  post_author = $10,
  post_mime_type = $11,
  published_by = $12,
  updated_by = $13
WHERE id = $1
RETURNING id, title, content, author_id, url, created_at, updated_at, status, published_at, edited_at, post_author, post_mime_type, published_by, updated_by
`

type UpdatePostsParams struct {
	ID           int64     `json:"id"`
	Title        string    `json:"title"`
	Content      string    `json:"content"`
	AuthorID     int64     `json:"author_id"`
	Url          string    `json:"url"`
	UpdatedAt    time.Time `json:"updated_at"`
	Status       string    `json:"status"`
	PublishedAt  time.Time `json:"published_at"`
	EditedAt     time.Time `json:"edited_at"`
	PostAuthor   string    `json:"post_author"`
	PostMimeType string    `json:"post_mime_type"`
	PublishedBy  string    `json:"published_by"`
	UpdatedBy    string    `json:"updated_by"`
}

func (q *Queries) UpdatePosts(ctx context.Context, arg UpdatePostsParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePosts,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.AuthorID,
		arg.Url,
		arg.UpdatedAt,
		arg.Status,
		arg.PublishedAt,
		arg.EditedAt,
		arg.PostAuthor,
		arg.PostMimeType,
		arg.PublishedBy,
		arg.UpdatedBy,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PublishedAt,
		&i.EditedAt,
		&i.PostAuthor,
		&i.PostMimeType,
		&i.PublishedBy,
		&i.UpdatedBy,
	)
	return i, err
}
