// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package frog_blossom_db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateMeta(ctx context.Context, arg CreateMetaParams) (Meta, error)
	CreatePages(ctx context.Context, arg CreatePagesParams) (Page, error)
	CreatePosts(ctx context.Context, arg CreatePostsParams) (Post, error)
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteMeta(ctx context.Context, id int64) error
	DeleteMetaByPageId(ctx context.Context, pageID sql.NullInt64) error
	DeleteMetaByPostId(ctx context.Context, postsID sql.NullInt64) error
	DeletePages(ctx context.Context, id int64) error
	DeletePosts(ctx context.Context, id int64) error
	DeleteUsers(ctx context.Context, id int64) error
	GetMeta(ctx context.Context, id int64) (Meta, error)
	GetMetaByPageIDForUpdate(ctx context.Context, pageID sql.NullInt64) (Meta, error)
	GetMetaByPostsIDForUpdate(ctx context.Context, postsID sql.NullInt64) (Meta, error)
	GetPages(ctx context.Context, id int64) (Page, error)
	GetPosts(ctx context.Context, id int64) (Post, error)
	GetUsers(ctx context.Context, id int64) (User, error)
	ListMeta(ctx context.Context, arg ListMetaParams) ([]Meta, error)
	ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateMeta(ctx context.Context, arg UpdateMetaParams) (Meta, error)
	UpdatePages(ctx context.Context, arg UpdatePagesParams) (Page, error)
	UpdatePosts(ctx context.Context, arg UpdatePostsParams) (Post, error)
	UpdateUsers(ctx context.Context, arg UpdateUsersParams) (User, error)
}

var _ Querier = (*Queries)(nil)
